[package]
name = "pshell"
version = "0.1.0"
authors = ["parth_shel <ps@parthshel.com>"]

[dependencies]
libc = "0.2.43"
rustyline = "2.1.0"
commands = "0.0.5"
hostname = "^0.1"
nix = "0.11.0"
glob = "0.2"
